### PR TITLE
Feature: Cluster

### PR DESCRIPTION
**Pull request by bklang**
This PR will allow for two roles within the app:
- Controller: The main web UI and system of record for storing app data
- Doors: The devices physically installed at the doors, who pull down/synchronize data from the Controller

There are several changes required to make this happen:
- [x] Allow provisioning to run on x86_64 systems
- [x] Configure PostgreSQL on the Controller role to be a replication master
- [x] Configure PostgreSQL on the Door role to be a replication slave
- [ ] Allow Gatekeeper to run with USB and GPIO disabled on the Controller
- [ ] Allow specifying the Door ID via provisioning
- [x] Split Reads/Writes to separate DB configurations

### CODE REVIEW

**Comment by benlangfeld** [comment]
What's the motivation for the following, @bklang?
- Make the Door role aware of the URL of the Controller
- Update the app to report access attempts to the Controller, and not log to the DB directly (and this process should be async to the door unlocking)

**Comment by bklang** [comment]
> - Make the Door role aware of the URL of the Controller
> - Update the app to report access attempts to the Controller, and not log to the DB directly (and this process should be async to the door unlocking)

PostgreSQL replication is one-way. The goal is to do AUTHZ locally against the read-only replica of the data, and then report the result to the controller so we have all access attempts logged in one place (and accessible via the web UI on the Controller).  This way all configuration and log review happens on the Controller (Postgres Master) and the Doors can still open while offline.

**Comment by benlangfeld** [comment]
Will the reporting be via HTTP or something else?

**Comment by benlangfeld** [comment]
> PostgreSQL replication is one-way.

It doesn't have to be: http://bdr-project.org/docs/stable/index.html

**Comment by bklang** [comment]
For posterity: bi-directional Postgres replication is too exotic for my comfort, and the built-in replication with split reads/writes works pretty well. The only hack was to make the tests work by referencing the same DB.  The only other thing I might consider in the future is switching to native Erlang clustering and use that to route DB writes to a master node, instead of relying on Postgres. But I'm happy enough with this for now.

**Pull request merged**
